### ISSUE TITLE
Angular Material compatibility

### ISSUE THREAD

**Issue by SNiels** [zavoloklom/material-design-iconic-font#10]
Many classes and directives use the prefix "md-", this causes to css of the Angular Material library to act strangely. Temporarily we have changed the prefix to "mdi-", where the "i" stands for icon.

**Comment by AdriVanHoudt** [comment]
:+1: https://github.com/zavoloklom/material-design-iconic-font/pull/4 would also work

**Comment by yamaryoxxxx** [comment]
+1

**Comment by kent-chiu** [comment]
+1

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)
