### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by nuragic** [zavoloklom/material-design-iconic-font#101]
Hello,

I'm trying to locate the following icons but seems they are not present so far:

https://design.google.com/icons/#ic_lightbulb_outline
https://design.google.com/icons/#ic_fitness_center
https://design.google.com/icons/#ic_gavel
https://design.google.com/icons/#ic_assignment
https://design.google.com/icons/#ic_business_center

Is that normal or is it a bug?

Thanks!

**Comment by LeleDev** [comment]
I'd like to have also unarchive icon imported (https://design.google.com/icons/#ic_unarchive).

Is an update of this library in progress, or not yet?
