### ISSUE TITLE
Grunt build issues

### ISSUE THREAD

**Issue by ajmajma** [zavoloklom/material-design-iconic-font#13]
Using grunt/yeoman/bower for an angular app using this, and this works great when I grunt serve, however when I ready for production and grunt build, and run the app.js in my dist folder - these fonts don't show up. Possible I'm missing something here, using this type of build is still new to me. Would appreciate any insight into getting these working, these icons are awesome!!

I know this is also addressed, but they are messing with my angular-material plugin as well.

Thanks!

**Comment by leonzinger** [comment]
For compatibility with angular-material there's a pull request i have added that solves that matter.

https://github.com/zavoloklom/material-design-iconic-font/pull/12

I have the same issue on deploy. i don't see the fonts, probably the path is broken...

**Comment by ajmajma** [comment]
Great! Thanks @leonzinger !
