### ISSUE TITLE
Add md-fw option like fa-fw in font awesome

### ISSUE THREAD

**Issue by LeleDev** [zavoloklom/material-design-iconic-font#15]
It would be really great to have a fixed-width class like with font awesome icons... it could be called 'md-fw'

Thank you in advance

**Comment by LeleDev** [comment]
(obviously if the icons are all already of the same width it wouldn't be necessary)

**Comment by zavoloklom** [comment]
I can do it, but what the point of this class?

**Comment by LeleDev** [comment]
To keep the content nearby the icons aligned, even with different icons sizes... for example, in a list of items like this
```
<div class="item"><i class="md md-flag"></i> Sample Text </div>
<div class="item"><i class="md md-delete"></i> Sample Text 2</div>
```
if the icons have different widths, the text will not be aligned between different rows

**Comment by nealrs** [comment]
:+1:

**Comment by zavoloklom** [comment]
Now icons not fixed-width by default, so this classes added in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)

**Comment by LeleDev** [comment]
Great! Is it intentional that the prefix for this (and some other classes) is 'zmd' instead of 'zmdi'

**Comment by zavoloklom** [comment]
Yes, but it can be discussed. 
I think that this allows you to keep separate icons and helper classes for next reason: we have helper class ```zmd-border``` for make icon bordered and also we have ```zmdi-border-clear``` for icon.
If make all prefixes the same it could be confusion and in some places they could possibly overlap in the future. 
Agree?

**Comment by LeleDev** [comment]
Ah ok now I've got it.
Mmh, this could be a bit confusing, especially for users coming from font-awesome I think... 

There are also two other possible approaches:
- in case of overlapping names, just try to find an alternative one for the helper classes (more font-awesome like solution)
- make a longer prefix for helper classes, like ```zmdi-hc-border```

I just find a bit confusing to have ```zmdi``` somewhere and ```zmd``` elsewhere...

**Comment by zavoloklom** [comment]
@LeleDev I think that second option is more perspective. 
I would release it solution (with old code for backward capability) in 2.1.0

**Comment by LeleDev** [comment]
ok, thank you!
