### ISSUE TITLE
Icon distorted, not rendered properly

### ISSUE THREAD

**Issue by dazhbog** [zavoloklom/material-design-iconic-font#16]
Hi I am using the battery icons and I just noticed that the icons are a bit distorted. See below.
I use 
`<i class="md md-battery-60 md-lg"></i>`

![image](https://cloud.githubusercontent.com/assets/1836262/5794518/fbf1e926-9f4f-11e4-9f22-b0c73bf09b5a.png)

![image](https://cloud.githubusercontent.com/assets/1836262/5794560/82212358-9f51-11e4-936b-889e4776de8f.png)

I played with the antializing settings and that seems to make it only worse. Is it the seed icon that has issues?

**Comment by zavoloklom** [comment]
Charging battery icon is normal? Can you upload pic of how other battery icons look like?

**Comment by dazhbog** [comment]
Yes sure!


![image](https://cloud.githubusercontent.com/assets/1836262/5804582/e9273aa8-9fe5-11e4-9d49-d0ce9445673b.png)

![image](https://cloud.githubusercontent.com/assets/1836262/5804599/1883dfe0-9fe6-11e4-8a39-0129c716910a.png)

This is from http://zavoloklom.github.io/material-design-iconic-font/icons.html
At different zoom levels, the overlapping lines show more and more.

Browser:
Google Chrome	39.0.2171.95 (Official Build) 
Revision	86b48442d063e82f94969f5439badf11c9baeacc-refs/branch-heads/2171@{#461}
OS	Mac OS X 
Blink	537.36 (@186555)
JavaScript	V8 3.29.88.17

**Comment by zavoloklom** [comment]
Thank you for information!
I don't see this effect on my pc (win8/Chrome), but i'm will try to fix it.

**Comment by zavoloklom** [comment]
This icons was removed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases).
