### ISSUE TITLE
Add App Window Title Icons

### ISSUE THREAD

**Issue by sondreb** [zavoloklom/material-design-iconic-font#17]
Please add the Chrome OS App Window Title Icons, by that I mean the minimize, maximize, close icons. Additionally it would be nice if you could add OS X versions of those same icons and the new full screen icon that was released with latest Windows 10 build.

I'm building a Chrome App for all platforms that uses a custom window chrome, so I need to render those icons on my own for all OS's.

**Comment by zavoloklom** [comment]
I don't draw icons, but if you can send me this icons (as SVG files or if you find them on [community page](https://materialdesignicons.com/)) - I would add them in next release.

**Comment by zavoloklom** [comment]
Added in [2.1.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.1.0)
