### ISSUE TITLE
md-lg offsets icon vertically in Safari

### ISSUE THREAD

**Issue by membla** [zavoloklom/material-design-iconic-font#18]
OSX Safari: (Shifted down)
![image](https://cloud.githubusercontent.com/assets/1955910/5905475/eceb4ba6-a5c2-11e4-9cd4-fe03b46e973d.png)

OSX Chrome: (Looks correct)
![image](https://cloud.githubusercontent.com/assets/1955910/5905493/09405ca6-a5c3-11e4-9bed-7efbee2dbe8a.png)

Removing the vertical-align:-35% fixes the issue in Safari but unsurprisingly messes it up in Chrome..

**Comment by zavoloklom** [comment]
It seems to be fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases), check it please.

**Comment by Denni007** [comment]
Yes its fixed

**Comment by zavoloklom** [comment]
@Denni007 Thank you!
