### ISSUE TITLE
Avoid wildcard selectors

### ISSUE THREAD

**Issue by elegos** [zavoloklom/material-design-iconic-font#21]
Hello!

I'm developing a framework which uses md-* class names. It works flawlessy, if it wasn't that you use two generic selectors to get all md-* items. As you use a name templating similar to FontAwesome (fa fa-* -> md md-*), why are you using these selectors? Also, these selectors are slower than "precise" ones (and I suppose this is why fontawesome avoids wildcards).

The selectors are:

`[class*=" md-"], [class^="md-"]`

I'd probably resolve and request a pull if I wasn't at work.

Thanks

**Comment by elegos** [comment]
Quickly viewing the source code, I don't understand why, in `_core.scss`, you make two selectors for the same item, as icons need both `md` and `md-icon-name` classes... a fix I did locally (in the minified CSS version, but should work flawlessy), is to use only the `.#{$md-css-prefix}` selector for all the file's properties.

**Comment by elegos** [comment]
Added pull request https://github.com/zavoloklom/material-design-iconic-font/pull/22

**Comment by jonny2779** [comment]
This is absolutely needed. I was about to make the same PR myself. Having the md- conflicts with much of the angular-material css files.

**Comment by joanrm20** [comment]
@jonny2779 that's true.. Facing the same issue right now integrating the md-slider from angular material

+1 for @elegos PR

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)
