### ISSUE TITLE
Font not icomoon ready

### ISSUE THREAD

**Issue by dingo-d** [zavoloklom/material-design-iconic-font#24]
Hi!

It would be cool if you would include either a simple icon list (the current cheatsheet is showing strange symbols instead of icon names), or a json file with icon names so that it can be uploaded to icomoon (icomoon exports the icons and creates a cheatsheet for you).

For now if you upload svg to icomoon you get icons, but the names start with uniF codes, and that's not user friendly.

**Comment by tomByrer** [comment]
Good idea if this repo would be around for a few years, but hopefully will be [superseded soon](https://github.com/google/material-design-icons/issues/1).

**Comment by dingo-d** [comment]
They added material icons to icoomoon so there is no need for this. :) Closing
