### ISSUE TITLE
sass variables should use !default for overriding

### ISSUE THREAD

**Issue by leemason** [zavoloklom/material-design-iconic-font#26]
currently you have to edit the variables.scss file directly to change variables when including in a different sass project.

this can negated by simply adding !default after the variable declaration in the variables file which will allow sass to override it by defining the variable before importing the file:

in _variables.scss
$md-font-path: "../fonts" !default;

in another sass project
$md-font-path: "../fonts/icons";
@import "material-design-iconic-font";

**Comment by Ollo** [comment]
:+1: I'm running into the same issue which makes this pretty un-usable via bower.

**Comment by jo4santos** [comment]
+1

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)
