### ISSUE TITLE
Feature request: Include Community Icons

### ISSUE THREAD

**Issue by boustanihani** [zavoloklom/material-design-iconic-font#27]
It would be nice if additional community icons also become part of this package:
http://materialdesignicons.com/

And also other essential icons like **youtube-play** for example:
http://materialdesignicons.com/icon/youtube-play

**Comment by zavoloklom** [comment]
I will add some of community icons in next release. But I'm interesting of where did you find 'Google' icons, cause some of them is not introduced in google-icons repository?

**Comment by zavoloklom** [comment]
Added some icons in [2.1.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.1.0)
If you want to add something specific - make new issue.

**Comment by boustanihani** [comment]
@zavoloklom nice work. Which google-icons repository where you talking about ?

**Comment by zavoloklom** [comment]
@boustanihani 
On materialdesignicons there is (for example) 'file-excel-box' marked as 'Google'. But in [material-design-icons](https://github.com/google/material-design-icons) I can't find it. Maybe it was maintained early and in other place?
`

**Comment by boustanihani** [comment]
@zavoloklom I have also no clue :bowtie:
