### ISSUE TITLE
md-label icon conflicts with angular-material's md-checkbox

### ISSUE THREAD

**Issue by spinningarrow** [zavoloklom/material-design-iconic-font#39]
The `md-label` icon seems to be conflicting with angular-material's `mdCheckbox` (https://material.angularjs.org/#/demo/material.components.checkbox). I get an extra label icon from the material-design-iconic-font, which shouldn't be there (only the text label of the checkbox is supposed to be there in the screenshot).

Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/1797328/7406462/d8cc519e-ef35-11e4-8179-e0d0bbe491ea.png)

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)
