### ISSUE TITLE
Social section doesn't show up when adblock is on

### ISSUE THREAD

**Issue by er40** [zavoloklom/material-design-iconic-font#41]
I am using Adgaurd AdBlocker and was using the cheatsheet page to copy icons into photoshop. Noticed the social section isn't there at all. Turned off adblock and it appeared.

Might want to add a note (unless there already is one I didn't see) to turn off adblock on this page.

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)
