### ISSUE TITLE
change default prefix to mdi

### ISSUE THREAD

**Issue by gitawego** [zavoloklom/material-design-iconic-font#44]
Could you please change default prefix to ``mdi`` instead of ``md`` ? because there is conflict with angular-material, or set variables configurable by adding !default so we can easily change the prefix:
```scss
$md-font-path: "../fonts" !default;
$md-css-prefix: md !default;
$md-version: "1.1.1";

$md-border-color: gray !default;
```

thanks a lot.

**Comment by zavoloklom** [comment]
Default prefix now is 'zmdi' in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)
