### ISSUE TITLE
"!default" not used properly in version 2.0.0

### ISSUE THREAD

**Issue by cgx** [zavoloklom/material-design-iconic-font#45]
From the [Changelog](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.0.0) of release 2.0.0:

> add "!default" to sass variables;

However, _!default_ is assigned to CSS declarations, **not** SASS variables. [libsass](http://libsass.org/]) doesn't like it.

See the [SASS documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_).

**Comment by zavoloklom** [comment]
Basicly I don't use SASS, I use LESS. 
So I don't understand what actualy i'm doing wrong cause i follow issue #26 and pull requests #23 and #25 recommendations.
Can you give me an example of what you think i should do in this files?
https://github.com/zavoloklom/material-design-iconic-font/blob/master/scss/_variables.scss
https://github.com/zavoloklom/material-design-iconic-font/blob/master/scss/_icons.scss

**Comment by cgx** [comment]
Those two files are correct. The problems are in `_sizes.scss`, `_stacked.scss` and `_rotated.scss`.

Simply remove the `!default` in those three files.

**Comment by zavoloklom** [comment]
Fix in [v2.0.1](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.0.1)
