### ISSUE TITLE
icons names in version 2.0.0

### ISSUE THREAD

**Issue by cgx** [zavoloklom/material-design-iconic-font#46]
Many icons names have changed in 2.0.0 but they are not (yet?) documented and they don't seem to match the names of the official [Google icons](https://www.google.com/design/icons/). Example:

| 1.1.1 | 2.0.0 | Google |
---------|--------|----------|
| create | edit | mode_edit |
| event | calendar | insert_invitation |
| settings-power | power-off-setting | settings-power |

**Comment by zavoloklom** [comment]
Yes. New docs are in progress. 
While it not finished you can switch to to github branch gh-pages-ver2 to see new names in icons.html page.

**Comment by cgx** [comment]
Cool. Thanks!

**Comment by LeleDev** [comment]
It would be appreciated to have a changelog for renamed icons in order to upgrade easily from the old version

**Comment by zavoloklom** [comment]
@LeleDev I think about it, but I can't promise that it could be created soon.
If someone want to help - I would be grateful.

**Comment by zavoloklom** [comment]
Docs are updated for v2.0.2.
See new [icons](http://zavoloklom.github.io/material-design-iconic-font/icons.html) and [examples](http://zavoloklom.github.io/material-design-iconic-font/examples.html) pages.

**Comment by zavoloklom** [comment]
Old docs are available here: [1.x docs](http://zavoloklom.github.io/material-design-iconic-font/v1/).
If someone can help me to create renamed icons table - I would be appreciate.

**Comment by Jogai** [comment]
My findings (without prefix):
messenger -> comment
description -> file-text
account-child -> accounts
public -> globe
verified-user -> shield-check
file-upload -> upload (with minor differece)

**Comment by zavoloklom** [comment]
@Jogai Thank you!
All renamed icons and guide for upgrading from 1.x: http://zavoloklom.github.io/material-design-iconic-font/v1/

**Comment by LeleDev** [comment]
Thank you! :)
