### ISSUE TITLE
icons in version 2.0.2 do not match the cheatsheet

### ISSUE THREAD

**Issue by uytieu** [zavoloklom/material-design-iconic-font#47]
When I copy the icons from the cheatsheet and paste them into my application the wrong icon appears.

**Comment by zavoloklom** [comment]
It seems to be fixed, please check it. If not - discribe situation more detailed.

**Comment by uytieu** [comment]
@zavoloklom Thanks for taking a look into this. 

Here's my detailed description below if that helps:

So currently if I want to use one of the icons in Sketch, I have to go to the [cheatsheet](http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html) to select the icon I want to copy it (not the unicode). When I paste it into Sketch (application) I'm not getting the correct icon that I previously selected.

For example if I copy this icon (not the unicode):
![screen shot 2015-06-22 at 2 32 37 pm](https://cloud.githubusercontent.com/assets/882328/8293620/9c92217e-18eb-11e5-9be7-d6215e72b9ff.png)

I'm getting this when I paste it into Sketch:
![screen shot 2015-06-22 at 2 34 23 pm](https://cloud.githubusercontent.com/assets/882328/8293647/cebc88d8-18eb-11e5-8843-f36a3a966c6d.png)

**Comment by zavoloklom** [comment]
Do you reinstalled ttf file?
This look like when you paste icon into Sketch it using older font version.
I can't check it in Sketch, but I tried to make this operation in Word and Photoshop on Win8.1 and it worked correctly.
Be shure that font name in programm should be "Material-Design-Iconic-Font" or "Material-Design-Iconic-Font Regular".

**Comment by uytieu** [comment]
@zavoloklom everything is resolved now, +1 

I was able to have it working after I restarted my machine. 

Thanks again.
