### ISSUE TITLE
Is there any support - cheatsheet for the older-previous version of the icons? 

### ISSUE THREAD

**Issue by patriciapineda** [zavoloklom/material-design-iconic-font#48]
It's seems like all the icons have been renamed and therefore while installing with bower the names are missing

**Comment by zavoloklom** [comment]
You can update to new version with Bower if you want by command ```bower install material-design-iconic-font#~2 --save```. If something going wrong try to use ```bower install material-design-iconic-font --force-latest --save``` command.

However icon set and cheatsheet for previous version will be posted this week.

**Comment by zavoloklom** [comment]
@patriciapineda sorry, I misunderstood your question first.
Yes, icons are renamed. I will make changelog for icons names as I say in #46

**Comment by zavoloklom** [comment]
@patriciapineda Old docs are available here: [1.x docs](http://zavoloklom.github.io/material-design-iconic-font/v1/).
