### ISSUE TITLE
change font folder to fonts

### ISSUE THREAD

**Issue by Kryptonit3** [zavoloklom/material-design-iconic-font#49]
nuff said. :)

Pretty sure this is a standard naming schema. It is just semantics but having a font folder and a fonts folder drives me nuts!

**Comment by zavoloklom** [comment]
@Kryptonit3 I was little insane when I did it. Will be reversed in 2.1.0

**Comment by zavoloklom** [comment]
Fixed in [2.1.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.1.0)
