### ISSUE TITLE
webpack threw an error Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by Lobos** [zavoloklom/material-design-iconic-font#51]
I installed the font by "npm install material-design-iconic-font"，then import less file in my project, use webpack and less-loader compile css. 
It threw an error "Cannot resolve 'file' or 'directory' ...", cause couldn't find font dir in root. I must copy  the font dir from dist to root. It will be a problem when I publish my project. 
Is there any other way to solve this ?

**Comment by zavoloklom** [comment]
@Lobos You need to edit ```@md-font-path``` in variables.less following instruction that the font path is relative from your compiled CSS directory.

**Comment by Lobos** [comment]
It's worked. Thank you so much.
