### ISSUE TITLE
bower.json defines all CSS files to be included

### ISSUE THREAD

**Issue by gituon** [zavoloklom/material-design-iconic-font#56]
The bower.json defines dist/css/* as the main files. This causes grunt to include both the normal and the minified version.

**Comment by zavoloklom** [comment]
Fixed in [2.1.2](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.1.2)

**Comment by thandaanda** [comment]
Hi @zavoloklom , Can you change bower.json to include minified css only, right now grunt tasks injects  css with following path, resulting in
````GET http://localhost:9000/bower_components/material-design-iconic-font/dist/css/*.min.css ````

**Comment by zavoloklom** [comment]
Fixed in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0)
