### ISSUE TITLE
Icon Request: rss

### ISSUE THREAD

**Issue by dennify** [zavoloklom/material-design-iconic-font#58]
Hi Mr. Kupletsky,

I love material design iconic font, but I am missing an rss icon like:

![image](https://cloud.githubusercontent.com/assets/6861243/8695117/8eb149ae-2ae3-11e5-8a17-d807a00960b6.png)
It would be nice if you can add this

Best regards,
Dennis

**Comment by zavoloklom** [comment]
Added in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0)
