### ISSUE TITLE
Icon Request: group/ungroup

### ISSUE THREAD

**Issue by dennify** [zavoloklom/material-design-iconic-font#60]
Hi Mr. Kupletsky,

I love material design iconic font, but I am missing a group and an ungroup icon like:

![image](https://cloud.githubusercontent.com/assets/6861243/8695305/9114ed44-2ae4-11e5-86bd-77a0e5101f81.png)

It would be nice if you can add this

Best regards,
Dennis

**Comment by zavoloklom** [comment]
Added in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0)
