### ISSUE TITLE
Icon Request: spinner

### ISSUE THREAD

**Issue by dennify** [zavoloklom/material-design-iconic-font#61]
Hi Mr. Kupletsky,

I love material design iconic font, but I am missing a spinner icon like:
![image](https://cloud.githubusercontent.com/assets/6861243/8695360/dbe7977c-2ae4-11e5-84a2-b8b18616a798.png)
It would be nice if you can add this

Best regards,
Dennis

**Comment by zavoloklom** [comment]
Added in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0)
