### ISSUE TITLE
 Icon Request: shape

### ISSUE THREAD

**Issue by dennify** [zavoloklom/material-design-iconic-font#62]
Hi Mr. Kupletsky,

I love material design iconic font, but I am missing a shape icon like:
![image](https://cloud.githubusercontent.com/assets/6861243/8695407/1893f3d2-2ae5-11e5-867e-c5ac0eda6ba4.png)
It would be nice if you can add this

Best regards,
Dennis

**Comment by zavoloklom** [comment]
Added in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0)
