### ISSUE TITLE
Website: Icon categories are misplaced

### ISSUE THREAD

**Issue by adrianblp** [zavoloklom/material-design-iconic-font#63]
Yo, just saw a small quirk on the website and figured I'd make a ticket. On the page http://zavoloklom.github.io/material-design-iconic-font/icons.html there are the different categories of icons, however somewhere in the middle it's placed as Directional and then Map, however in the side menu it's Map and then Directional which leads to the highlight jumping a bit all over the place when scrolling down

**Comment by zavoloklom** [comment]
Thank you! Will fix it.
