### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by karimcossutti** [zavoloklom/material-design-iconic-font#65]
Some icons are broken, see attached screenshots

![schermata 2015-07-20 alle 17 25 31](https://cloud.githubusercontent.com/assets/878135/8779702/e6c64372-2f04-11e5-81f6-2e9b010bd201.png)
![schermata 2015-07-20 alle 17 25 51](https://cloud.githubusercontent.com/assets/878135/8779703/e6db9f56-2f04-11e5-86bf-b6c87f47477b.png)

**Comment by karimcossutti** [comment]
hey, i see you completed the milestone, any ETA on the release?

**Comment by zavoloklom** [comment]
@karimcossutti, I think that in September

**Comment by corymsmith** [comment]
@zavoloklom Any updates on when you may add the new icons? I'm using this in https://github.com/corymsmith/react-native-icons and have had a few issues reported around missing icons: corymsmith/react-native-icons#95 and corymsmith/react-native-icons#127.

Is there any way that we can help with a new version?

**Comment by zavoloklom** [comment]
Fixed in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0)
