### ISSUE TITLE
Icon request: social icons

### ISSUE THREAD

**Issue by diegodalbosco** [zavoloklom/material-design-iconic-font#67]
Hi, i like your job but I need some social icons. Can you add these?
http://www.socicon.com/chart.php
thanks

**Comment by zavoloklom** [comment]
Added some new social icons in [2.2.0](https://github.com/zavoloklom/material-design-iconic-font/releases/tag/2.2.0).

**Comment by zavoloklom** [comment]
@diegodalbosco, is it OK now or you want to add some specific social icons?

**Comment by diegodalbosco** [comment]
Now they're ok, thanks :+1:
