### ISSUE TITLE
New google icons - backspace

### ISSUE THREAD

**Issue by mbrookes** [zavoloklom/material-design-iconic-font#68]
Any plans to pull in the new icons from google? (Specifically https://www.google.com/design/icons/#ic_backspace for mobile apps)

Thanks!

**Comment by zavoloklom** [comment]
It is already in font.
Search for "tag-close" here http://zavoloklom.github.io/material-design-iconic-font/icons.html

**Comment by mbrookes** [comment]
Oh yeah - cool thanks. Confusing that the names are different! :confused: I'll look more carefully next time!
