### ISSUE TITLE
Icon request: Numeric icons

### ISSUE THREAD

**Issue by arichiardi** [zavoloklom/material-design-iconic-font#71]
I haven't seen them.

![selection_021](https://cloud.githubusercontent.com/assets/1724788/11073469/a4d6193a-879f-11e5-838f-ce76e447fe8f.png)

Thanks for your great work!

**Comment by zavoloklom** [comment]
@arichiardi,
names of this icons start with `collection-item` in **Web App** section. Also some of them are in [**Numbers sections**](http://zavoloklom.github.io/material-design-iconic-font/icons.html#numbers).

**Comment by arichiardi** [comment]
Oh ok great thanks a lot, I apologise I did not notice them :+1:
