### ISSUE TITLE
Update to the newest Google Material Icons v2.2

### ISSUE THREAD

**Issue by mikepenz** [zavoloklom/material-design-iconic-font#76]
Hey. 

Thanks for this great project. It really helped me, because the official web font has a few flaws. 
I just saw google released v2.1. of the Google Material Icons. 

It would be great if you could update to them. 

https://github.com/google/material-design-icons/

Thank you so much.

**Comment by bjarnef** [comment]
I would also love if the icon set can be updated with many of the latest icons https://design.google.com/icons/

Furthermore maybe the names can be consistent with naming in Material Design icon set, e.g. `star-outline` .. in the Material Design icons it is called `star-border`. It would make it easier to find the icons.

**Comment by mikepenz** [comment]
@zavoloklom ok now there is v2.2.0 with 41 new icons by google ;)

**Comment by bjarnef** [comment]
It would bedre nice if this project can be updated to include the recent material icons since there haven't been updates for 6 months.

**Comment by mikepenz** [comment]
seems like this project is dead. will stick with the original set, or the community material icons
